### ISSUE TITLE
'pip check' fails when tqdm 4.61.2 is installed from conda-forge on Windows.

### ISSUE THREAD

**Issue by danschef** [conda-forge/tqdm-feedstock#104]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

When I install tqdm 4.61.2 via conda-forge on Windows and run a 'pip check' afterwards, the following exception is raised:

**tqdm 4.61.2 requires colorama, which is not installed.**

It seems like the issue came up with tqdm 4.61.2 and I am running into the exception when trying to build my own conda-forge package arosics. Here is the Azure pipeline that fails: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=348165&view=logs&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=66e4a587-a723-53e9-873c-6c9a2c5971ea .

tqdm is required there as a third-level dependency of arosics (arosics -> holoviews -> panel -> tqdm)
For Linux and Mac OS, everything works fine.

**Comment by casperdcl** [comment]
Indeed, #103 shouldn't have been merged without adding the dep

**Comment by danschef** [comment]
Ok, so simply releasing a new build should do it.

**Comment by danschef** [comment]
@casperdcl Somehow `pip check` still fails on Windows with the same error as long as I don´t add colorama to the meta.yaml file of my package. See [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=350576&view=logs&jobId=4df4d378-e321-55ba-2201-2fae9d1dab78&j=4df4d378-e321-55ba-2201-2fae9d1dab78&t=c6f47b81-e655-562b-3dd0-a092d624d1cf) and [here](https://github.com/conda-forge/arosics-feedstock/pull/44).

I don´t really get why because Conda seems to correctly install build 1 of tqdm 4.61.2:

`tqdm:                    4.61.2-pyhd8ed1ab_1         conda-forge`

I added colorama now to my meta.yaml but this is only a workaround.
