### ISSUE TITLE
consider adding ipywidgets as a dependency

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/tqdm-feedstock#22]
tqdm supports progress bars for the notebook. In a conda environment where tqdm is installed but not `ipywidgets` package running `for i in tqdm_notebook(range(10))` will result in an error that `IntProgress` couldn't be found. 

Installing `ipywidgets` solves the issues. 

I understand if you don't want to add this as a dependency as it would only be a convenience to use the package with the notebook out of box. But of course, not everyone wants to run tqdm in the notebook and might not want to install the extra packages.

**Comment by casperdcl** [comment]
Thanks for suggesting this, but as you've said, we don't want to introduce hard dependencies for optional modules. Also please open issues on https://github.com/tqdm/tqdm/issues rather than the feedstock!

**Comment by ericdill** [comment]
@kain88-de [jupyter lists ipywidgets](https://github.com/conda-forge/jupyter-feedstock/blob/master/recipe/meta.yaml#L27) as a dependency so if you're in a conda environment where you're using jupyter you already have access to ipywidgets if you then conda install tqdm. Conversely if you're not in an environment with jupyter then you wouldn't even be able to use ipywidgets so it wouldn't make sense to have ipywidgets as a hard dependency

**Comment by kain88-de** [comment]
@ericdill jupyter isn't normally installed. You can try `conda create -n test nb_conda_kernels tqdm`. This will install everything needed to access the environment from a jupyter notebook started in the main environment. This will not install `jupyter` or `ipywidgets`  leading to the error when I try to use tqdm in the notebook.

**Comment by ericdill** [comment]
Ah so the use case is starting a jupyter server in one environment and using a kernel that doesn't have jupyter installed. My apologies for not understanding sooner. Thanks for clarifying.

**Comment by kain88-de** [comment]
But your comment is good. Maybe the solution is to add ipywidgets to either `nb_conda_kernels` or one of it's dependencies.
