### ISSUE TITLE
tqdm: 4.53.0 fails pip check

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/tqdm-feedstock#84]
Hi folks!

I've got a WIP over on https://github.com/conda-forge/dagster-feedstock/pull/87 where we `pip check` as part of the test procedure. With `tqdm 4.53.0-pyhd3deb0d_0` installed, I see:

```

The following NEW packages will be INSTALLED:

...

    tqdm:                          4.53.0-pyhd3deb0d_0         conda-forge      
...

+ python -m pip check
papermill 1.2.1 has requirement tqdm>=4.32.2, but you have tqdm 0.0.0.
```

Haven't dug into the upstream as to what might have changed... will investigate!

**Comment by jan-janssen** [comment]
I have the same issue.

**Comment by bollwyvl** [comment]
Turns out pip check won't help in this case, as tqdm does not depend on
itself. However I did add it in the linked pr, in case they _do_ take a
dependency at some point.

"pip check --setup-requires ." would be smooth.

If you're running into issues, you could make the
conda-forge/admin-requests to market build 0 broken, I'm away from keyboard.
