### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by tdegeus** [conda-forge/tqdm-feedstock#94]
With the latest `tqdm` on conda-forge I'm getting:

```
import tqdm
  File "/home/tdegeus/miniconda3/envs/code_velocity_s6g1/lib/python3.8/site-packages/tqdm/__init__.py", line 3, in <module>
    from .cli import main  # TODO: remove in v5.0.0
ValueError: source code string cannot contain null bytes
```

The version:

```
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
```

(on Linux).

Everything works fine when downgrading to `tqdm-4.55.2`. Strangely my Linux CI is not failing, which presumable uses the same package.

See https://github.com/tqdm/tqdm/issues/1117

**Comment by casperdcl** [comment]
Sorry missed this issue. Is it still a problem? https://github.com/tqdm/tqdm/issues/1117 looks resolved

**Comment by tdegeus** [comment]
I'm assuming it went away in some update too
